title: "Essa Imhmed"
logo: /assets/img/logo.png
description: "Assistant Professor of Computer Science | Researcher | Educator"
author: ""
# "Dr. Essa Imhmed"
email: essa.imhmed@enmu.edu
theme: jekyll-theme-minimal
