title: Essa Imhmed, Ph.D.
logo: /assets/img/logo.png
description: Tenure Track Assistant Professor <br> Educator | Researcher
# Eastern New Mexico University
# JWLA 211 K | your.email@enmu.edu
show_menu: true
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
